<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE students [
  <!ELEMENT students (student) >
    <!ELEMENT student (firstname, lastname) >
    <!ELEMENT firstname (#PCDATA)>
    <!ELEMENT lastname (#PCDATA)>
]>
<students xmlns="http://rmecab.jp" >
     <student>
      <firstname>基広</firstname>
      <lastname>石田</lastname>
   </student>
   <student>
      <firstname>太祐</firstname>
      <lastname>市川</lastname>
   </student>
   <student>
      <firstname>真也</firstname>
      <lastname>瓜生</lastname>
   </student>
   <student>
      <firstname>啓明</firstname>
      <lastname>湯谷</lastname>
   </student>
 </students>
